"""
LLM-generated bread-coffee pairing matrix.

On first use, calls DeepSeek to score all 6 breads x 8 coffees based on
flavor profiles. Result is cached in memory for instant retrieval.

Fallback: hardcoded matrix if DeepSeek unavailable.
"""

import json
import logging
import httpx, os

def _call_deepseek(prompt: str, system: str = "", max_tokens: int = 2000) -> str:
    key = os.getenv("DEEPSEEK_API_KEY", "")
    if not key:
        raise RuntimeError("DEEPSEEK_API_KEY not set")
    url = os.getenv("DEEPSEEK_BASE_URL", "https://api.deepseek.com/v1") + "/chat/completions"
    messages = []
    if system:
        messages.append({"role": "system", "content": system})
    messages.append({"role": "user", "content": prompt})
    resp = httpx.post(url,
        headers={"Authorization": f"Bearer {key}", "Content-Type": "application/json"},
        json={"model": os.getenv("DEEPSEEK_MODEL", "deepseek-v4-flash"), "messages": messages,
              "max_tokens": max_tokens, "temperature": 0.3},
        timeout=30)
    resp.raise_for_status()
    return resp.json()["choices"][0]["message"]["content"]

logger = logging.getLogger("s4.pairing")

# Cache
_pairing_cache: dict | None = None

def _load_bakery_products():
    """Load all bakery products from DB for pairing matrix generation."""
    import sys, os
    sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..'))
    from db.mysql_client import get_db
    db = get_db()
    cur = db.cursor()
    cur.execute("SELECT product_name FROM products WHERE category='bakery' ORDER BY product_name")
    products = []
    for r in cur.fetchall():
        key = r[0]
        name = key.replace('_', ' ').title()
        products.append({"key": key, "name": name, "desc": name})
    cur.close()
    db.close()
    return products

_BAKERY_CACHE = None
def _get_bakery():
    global _BAKERY_CACHE
    if _BAKERY_CACHE is None:
        _BAKERY_CACHE = _load_bakery_products()
    return _BAKERY_CACHE
BAKERY = None  # Use _get_bakery() instead

def _load_coffee_products():
    """Load all beverage products from DB for pairing matrix generation."""
    import sys, os
    sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..'))
    from db.mysql_client import get_db
    db = get_db()
    cur = db.cursor()
    cur.execute("SELECT product_name FROM products WHERE category='beverage' ORDER BY product_name")
    products = []
    for r in cur.fetchall():
        key = r[0]
        name = key.replace('_', ' ').title()
        products.append({"key": key, "name": name, "desc": name})
    cur.close()
    db.close()
    return products

_COFFEE_CACHE = None
def _get_coffee():
    global _COFFEE_CACHE
    if _COFFEE_CACHE is None:
        _COFFEE_CACHE = _load_coffee_products()
    return _COFFEE_CACHE
COFFEE = None  # Use _get_coffee() instead

# Hardcoded fallback matrix
def _build_fallback_matrix():
    """Build a default pairing matrix when DeepSeek is unavailable.
    All pairs default to 0.5 (neutral)."""
    matrix = {}
    for b in _get_bakery():
        bk = b["key"]
        matrix[bk] = {}
        for c in _get_coffee():
            matrix[bk][c["key"]] = 0.5
    return matrix

FALLBACK_MATRIX = None  # Built lazily via _build_fallback_matrix()


def generate_pairing_matrix() -> dict:
    """Call DeepSeek to score every bread x coffee pair (0.0-1.0)."""
    try:
        prompt = _build_pairing_prompt()
        system = (
            "You are a professional bakery and coffee pairing expert. "
            "Score each bread-coffee pair from 0.0 (terrible match) to 1.0 (perfect match). "
            "Consider flavor complementarity, texture contrast, and traditional pairing wisdom. "
            "Return ONLY valid JSON with no commentary."
        )
        response = _call_deepseek(prompt, system, max_tokens=2000)
        matrix = json.loads(response)
        # Validate structure
        for bread in _get_bakery():
            bk = bread["key"]
            if bk not in matrix:
                raise ValueError(f"Missing bread: {bk}")
            for coffee in _get_coffee():
                ck = coffee["key"]
                if ck not in matrix[bk]:
                    matrix[bk][ck] = 0.3
                matrix[bk][ck] = max(0.0, min(1.0, float(matrix[bk][ck])))
        logger.info("Pairing matrix generated by DeepSeek")
        return matrix
    except Exception as e:
        logger.warning("DeepSeek pairing matrix unavailable (%s), using fallback", e)
        return _build_fallback_matrix()

def get_pairing_matrix(force_refresh: bool = False) -> dict:
    """Get the pairing matrix (cached after first generation)."""
    global _pairing_cache
    if force_refresh or _pairing_cache is None:
        _pairing_cache = generate_pairing_matrix()
    return _pairing_cache


def _build_pairing_prompt() -> str:
    lines = ["Score every bread-coffee pair (0.0-1.0) based on flavor compatibility.\n"]
    lines.append("Breads:")
    for b in _get_bakery():
        lines.append(f"  - {b['key']}: {b['desc']}")
    lines.append("\nCoffees:")
    for c in _get_coffee():
        lines.append(f"  - {c['key']}: {c['desc']}")
    lines.append("\nReturn JSON like:")
    example = {}
    for b in _get_bakery()[:2]:
        example[b["key"]] = {c["key"]: 0.5 for c in COFFEE[:2]}
    lines.append(json.dumps(example, indent=2))
    lines.append("\nInclude ALL breads and ALL coffees listed above. Scores must be 0.0-1.0.")
    return "\n".join(lines)
