"""
LLM-generated bread-coffee pairing matrix.

On first use, calls DeepSeek to score all 6 breads x 8 coffees based on
flavor profiles. Result is cached in memory for instant retrieval.

Fallback: hardcoded matrix if DeepSeek unavailable.
"""

import json
import logging
from api.module5_agent.llm_client import call_deepseek

logger = logging.getLogger("s4.pairing")

# Cache
_pairing_cache: dict | None = None

BAKERY = [
    {"key": "donut", "name": "Donut", "desc": "sweet fried dough, glazed or sugared, soft and airy"},
    {"key": "croissant", "name": "Croissant", "desc": "buttery flaky laminated pastry, rich and layered"},
    {"key": "bread_coconut", "name": "Coconut Bread", "desc": "soft bread with sweet shredded coconut filling"},
    {"key": "bread_roll", "name": "Bread Roll", "desc": "plain soft dinner roll, mild and versatile"},
    {"key": "chiffon", "name": "Chiffon Cake", "desc": "light airy cotton-soft sponge cake, mildly sweet"},
    {"key": "croissant_chocolate", "name": "Chocolate Croissant", "desc": "flaky croissant with rich dark chocolate filling"},
]

COFFEE = [
    {"key": "latte", "name": "Latte", "desc": "smooth steamed milk with espresso, creamy and mild"},
    {"key": "americano", "name": "Americano", "desc": "espresso diluted with hot water, clean and bold"},
    {"key": "cappuccino", "name": "Cappuccino", "desc": "espresso with thick milk foam, strong and frothy"},
    {"key": "cold_brew", "name": "Cold Brew", "desc": "cold-steeped smooth coffee, low acidity, chocolate notes"},
    {"key": "espresso", "name": "Espresso", "desc": "concentrated intense coffee shot, bold and short"},
    {"key": "flat_white", "name": "Flat White", "desc": "velvety microfoam milk with espresso, silky texture"},
    {"key": "mocha", "name": "Mocha", "desc": "espresso with chocolate syrup and steamed milk, sweet indulgence"},
    {"key": "iced_americano", "name": "Iced Americano", "desc": "chilled americano over ice, refreshing and crisp"},
]

# Hardcoded fallback matrix
FALLBACK_MATRIX = {
    "donut":              {"latte": 0.9, "americano": 0.7, "cappuccino": 0.6, "mocha": 0.8},
    "croissant":          {"latte": 1.0, "cappuccino": 0.9, "flat_white": 0.8, "espresso": 0.7},
    "bread_coconut":      {"americano": 0.8, "cold_brew": 0.7, "latte": 0.6},
    "bread_roll":         {"latte": 0.7, "cappuccino": 0.6, "americano": 0.8},
    "chiffon":            {"cold_brew": 0.9, "iced_americano": 0.8, "mocha": 0.7},
    "croissant_chocolate":{"mocha": 1.0, "latte": 0.9, "cappuccino": 0.8, "espresso": 0.7},
}


def generate_pairing_matrix() -> dict:
    """Call DeepSeek to score every bread x coffee pair (0.0-1.0)."""
    prompt = _build_pairing_prompt()
    system = (
        "You are a professional bakery and coffee pairing expert. "
        "Score each bread-coffee pair from 0.0 (terrible match) to 1.0 (perfect match). "
        "Consider flavor complementarity, texture contrast, and traditional pairing wisdom. "
        "Return ONLY valid JSON with no commentary."
    )
    response = call_deepseek(prompt, system, max_tokens=2000)
    try:
        matrix = json.loads(response)
        # Validate structure
        for bread in BAKERY:
            bk = bread["key"]
            if bk not in matrix:
                raise ValueError(f"Missing bread: {bk}")
            for coffee in COFFEE:
                ck = coffee["key"]
                if ck not in matrix[bk]:
                    matrix[bk][ck] = 0.3
                matrix[bk][ck] = max(0.0, min(1.0, float(matrix[bk][ck])))
        logger.info("Pairing matrix generated by DeepSeek")
        return matrix
    except (json.JSONDecodeError, ValueError, KeyError) as e:
        logger.warning("DeepSeek pairing matrix invalid (%s), using fallback", e)
        return FALLBACK_MATRIX


def get_pairing_matrix(force_refresh: bool = False) -> dict:
    """Get the pairing matrix (cached after first generation)."""
    global _pairing_cache
    if force_refresh or _pairing_cache is None:
        _pairing_cache = generate_pairing_matrix()
    return _pairing_cache


def _build_pairing_prompt() -> str:
    lines = ["Score every bread-coffee pair (0.0-1.0) based on flavor compatibility.\n"]
    lines.append("Breads:")
    for b in BAKERY:
        lines.append(f"  - {b['key']}: {b['desc']}")
    lines.append("\nCoffees:")
    for c in COFFEE:
        lines.append(f"  - {c['key']}: {c['desc']}")
    lines.append("\nReturn JSON like:")
    example = {}
    for b in BAKERY[:2]:
        example[b["key"]] = {c["key"]: 0.5 for c in COFFEE[:2]}
    lines.append(json.dumps(example, indent=2))
    lines.append("\nInclude ALL 6 breads and ALL 8 coffees. Scores must be 0.0-1.0.")
    return "\n".join(lines)
